Занятие 2: Объекты
js-tasks-ru/jsbasic-20231109_georgiy-dronov pull request #3
Opened 2023-11-18 12:26 UTC by georgdronov

Решены задачи:
[Функция sumSalary(salaries)](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/2-module/1-task)
[Определите, пуст ли объект](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/2-module/2-task)
[Создайте калькулятор](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/2-module/3-task)

2023-11-18 12:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-18 13:03 UTC, SinimaWath requested changes

2023-11-18 13:03 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  let keyCount = null;
по-умолчанию у тебя количество ключей равно: `0`. Поэтому стоит писать `let keyCount = 0`, а не null

2023-11-18 13:03 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  return true
Стоит упростить до `return keyCount === 0`;

2023-11-18 13:03 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    this.b = arguments[1]
Это достаточно устаревшая конструкция, давай использовать просто аргументы функции:
```
read(a, b) {
  this.a = a;
  this.b = b;
}
```

2023-11-18 14:14 UTC, georgdronov commented on 2-module/2-task/index.js
> +  let keyCount = null;
Понял, поправил

2023-11-18 14:15 UTC, georgdronov commented on 2-module/2-task/index.js
> +  return true
Понял поправил

2023-11-18 14:16 UTC, georgdronov commented on 2-module/3-task/index.js
> +    this.b = arguments[1]
Не знал что так можно)
Спасибо)

2023-11-18 14:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-19 11:11 UTC, SinimaWath approved these changes

2023-11-19 11:11 UTC, merged