Решены задачи модуля №6
js-tasks-ru/jsbasic-20231109_georgiy-dronov pull request #7
Opened 2023-12-06 09:00 UTC by georgdronov

Решены задачи:
[Таблица с удаляемыми строками](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/6-module/1-task)
[Учебный проект: Карточка товара](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/6-module/2-task)
[Учебный проект: Карусель](https://learn.javascript.ru/taskbook/jsbasic-20231109/workspace/6-module/3-task)

2023-12-06 09:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-12-06 13:06 UTC, SinimaWath requested changes

2023-12-06 13:06 UTC, SinimaWath commented on 6-module/1-task/index.js
> +        <td><button onclick="this.parentNode.parentNode.remove()">X</button></td>
Выглядит очень костыльно, давай не использовать такой подход.

К примеру: `tr.querySelector('button')` - а лучше добавить, какой либо селектор: `<button data-action="remove">X</button>` - `tr.querySelector('[data-action="remove"]')`

2023-12-06 13:06 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    })
nit: кажется, тебе это здесь не надо в этом коде.

2023-12-06 14:18 UTC, georgdronov commented on 6-module/1-task/index.js
> +        <td><button onclick="this.parentNode.parentNode.remove()">X</button></td>
Поправил на селектор и проверку нажата ли кнопка

2023-12-06 14:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-12-06 14:18 UTC, georgdronov commented on 6-module/3-task/index.js
> +    })
Убрал

2023-12-10 10:20 UTC, SinimaWath approved these changes

2023-12-10 10:21 UTC, merged